name: barrage_video
description: mask barrage video demo.
version: 1.0.0

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  event_bus: ^1.1.0
  video_player: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/yoona.mp4
  - assets/mask.json
